### ISSUE TITLE
StatusCodeError 404

### ISSUE THREAD

**Issue by sourav-prescriber-360** [hhawkins/generator-azurefunctions#4]
Received this error for Javascript as Language
` {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}
    at new StatusCodeError (/usr/local/lib/node_modules/generator-azurefunctions/node_modules/@request/promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/generator-azurefunctions/node_modules/@request/promise-core/lib/plumbing.js:95:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/generator-azurefunctions/node_modules/@request/promise-core/lib/plumbing.js:37:31)
    at Request.self.callback (/usr/local/lib/node_modules/generator-azurefunctions/node_modules/request/request.js:185:22)
`

**Comment by billbatista** [comment]
Getting the same error here, tried different languages and types.
